/**
 * @freeside/gate-leak-protocol
 *
 * CR-002: the ratified Gate Leak recipe. Versioned capability declarations,
 * canonical work-key input schemas, safe public reason codes, the immutable
 * gate-mapping aggregate, evidence alignment and watermark restart rules, and
 * the one-directional classification / coverage / disclosure-band contracts.
 *
 * Builds on CR-001 (`@freeside/collection-protocol`) for identity, canonical
 * encoding, and digest semantics; it never restates them.
 */

export {
  GATE_LEAK_PROTOCOL_VERSION,
  GATE_LEAK_PROTOCOL_SCHEMA_VERSION,
  DiscordSnowflake,
  CommunityRef,
  SubjectRef,
  DecimalString,
  IsoTimestamp,
  OperatorPermission,
  GATE_CONFIG_RATIFY_PERMISSION,
  PRIVACY_APPROVE_GATE_AUDIT_PERMISSION,
  COMMUNITY_GATE_AUDIT_PURPOSE,
} from "./scalars.js";

export {
  GateLeakOrderReasonCode,
  GateLeakRowReasonCode,
  EligibilityState,
  GATE_LEAK_ORDER_REASON_CODES,
  GATE_LEAK_ORDER_REASON_CODE_ORDER,
  GATE_LEAK_ROW_REASON_CODES,
  GATE_LEAK_SCOPE_STATEMENT,
  orderGateLeakOrderReasonCodes,
  type OrderReasonCodeEntry,
  type RowReasonCodeEntry,
} from "./reason-codes.js";

export {
  GATE_LEAK_DIGEST_DOMAINS,
  GateRuleV1,
  GATE_RULE_V1,
  UNSUPPORTED_GATE_RULE_KINDS,
  UnsupportedGateRuleKind,
  RequestedGateRule,
  UnsupportedGateRuleError,
  admitGateRule,
  digestGateRule,
} from "./gate-rule.js";

export {
  GateLeakCapabilityId,
  ShareabilityScope,
  PrivacyClass,
  EvidenceBoundaryDerivation,
  PartialPolicy,
  DeploymentCoverageRequirement,
  GATE_LEAK_CAPABILITIES,
  GATE_LEAK_RECIPE_V1,
  GATE_LEAK_COVERAGE_POLICY_V1,
  GATE_LEAK_DISCLOSURE_POLICY_V1,
  GATE_LEAK_CHURN_POLICY_V1,
  DISCORD_CAPTURE_POLICY_V1,
  DISCORD_SNAPSHOT_FRESHNESS_POLICY_V1,
  OWNERSHIP_FRESHNESS_POLICY_V1,
  OWNERSHIP_FINALITY_EIP155_FINALIZED_BLOCK_V1,
  OWNERSHIP_FINALITY_SOLANA_FINALIZED_COMMITMENT_V1,
  OWNERSHIP_FINALITY_POLICY_VERSIONS_V1,
  OWNERSHIP_FINALITY_POLICY_BY_NAMESPACE_V1,
  OwnershipFinalityPolicyVersion,
  IDENTITY_SNAPSHOT_FRESHNESS_POLICY_V1,
  CLOCK_SKEW_POLICY_V1,
  SUBJECT_COHORT_POLICY_V1,
  EVIDENCE_ALIGNMENT_POLICY_V1,
  PolicyVersionRef,
  type GateLeakCapabilityDeclaration,
  type GateLeakRecipe,
  type GateLeakRecipeRequirement,
  type RecipeFreshnessRequirement,
  type OwnershipFinalityPolicyVersionV1,
} from "./capabilities.js";

export {
  RoleIdSet,
  EmptyDeploymentSelectionError,
  InvalidDeploymentSetMemberError,
  validateSelectedDeploymentSet,
  canonicalDeploymentIdSet,
  canonicalRoleIdSet,
  digestDeploymentSet,
  ContinuousLatestBoundary,
  MappingVersionBoundary,
  AcquisitionBoundary,
  ExactSnapshotBoundary,
  SnapshotEvidenceBoundary,
  SubjectCohortRef,
  ComputeResultScope,
  CollectionIdentityWorkKeyInput,
  OwnershipIndexWorkKeyInput,
  GateMappingWorkKeyInput,
  DiscordRoleSnapshotWorkKeyInput,
  IdentityLinkSnapshotWorkKeyInput,
  GateLeakComputeWorkKeyInput,
  GateLeakWorkKeyInput,
  decodeGateLeakWorkKeyInput,
  decodeSubjectCohortRef,
  digestGateLeakWorkKey,
} from "./work-keys.js";

export {
  RatifiedMappingProvenance,
  IdentityRevealBasis,
  GateMappingCommandMaterial,
  GateMappingVersion,
  GateMappingHypothesis,
  GateMappingAuditEvent,
  GateMappingAggregate,
  computeGateMappingConfigDigest,
  computeGateMappingCommandDigest,
  verifyGateMappingVersionIntegrity,
  decodeGateMappingVersion,
  decodeGateMappingAggregate,
  decodeGateMappingHypothesis,
  RatifyGateMappingCommand,
  decodeRatifyGateMappingCommand,
  RevokeGateMappingCommand,
  decodeRevokeGateMappingCommand,
  ratifyGateMapping,
  revokeGateMappingVersion,
  mappingSatisfiesReadiness,
  mappingPermitsIdentityReveal,
  evaluateGateLeakOrderChurn,
  UnauthorizedRatifierError,
  MappingVersionConflictError,
  ActiveMappingExistsError,
  MalformedMappingAggregateError,
  MappingIntegrityError,
  IntegrationEvidenceMismatchError,
  MappingChurnLimitError,
  SecondApproverInvalidError,
  MappingVersionNotFoundError,
  MappingAlreadyRevokedError,
  MappingScopeMismatchError,
  IdempotencyConflictError,
  type GateMappingConfigMaterial,
  type RatifyGateMappingResult,
  type RevokeGateMappingResult,
  type MappingReadinessVerdict,
  type IdentityRevealVerdict,
  type OrderChurnVerdict,
} from "./mapping.js";

export {
  ObservationWindow,
  checkEvidenceAlignment,
  CollectionIdentityEvidence,
  Eip155FinalizedBlockAttestation,
  SolanaFinalizedCommitmentAttestation,
  OwnershipFinalityAttestation,
  computeOwnershipFinalityAttestationDigest,
  verifyOwnershipFinalityAttestationIntegrity,
  OwnershipFinalityIntegrityError,
  OwnershipIndexEvidence,
  DiscordCaptureAttestation,
  DiscordRoleSnapshotEvidence,
  ConsentProvenance,
  InvalidationProvenance,
  RetentionBound,
  IdentityLinkSnapshotEvidence,
  decodeCollectionIdentityEvidence,
  decodeOwnershipIndexEvidence,
  decodeDiscordRoleSnapshotEvidence,
  decodeIdentityLinkSnapshotEvidence,
  AuthorizationWatermark,
  AuthorizationWatermarkSet,
  compareAuthorizationWatermarks,
  canonicalAuthorizationWatermarkSet,
  authorizationWatermarkSetsEqual,
  ComputeAttemptPins,
  decodeComputeAttemptPins,
  evaluateWatermarkRestart,
  qualifiesForReuse,
  observationAgeSecondsAt,
  evaluateOwnershipFreshnessAt,
  evaluateOwnershipFinalityProof,
  buildVerifiedDeploymentNetworkMap,
  evaluateDiscordSnapshotFreshnessAt,
  evaluateIdentitySnapshotFreshnessAt,
  type DeploymentNetworkNamespace,
  type VerifiedDeploymentNetworkMap,
  type EvidenceAlignmentVerdict,
  type WindowGap,
  type ObservedMutations,
  type WatermarkRestartDecision,
  type EvidenceReuseCandidate,
  type EvidenceRequirementContext,
  type EvidenceReuseVerdict,
  type CapabilityFreshnessVerdict,
  type OwnershipFinalityAttestationMaterial,
  type OwnershipFinalityReadinessVerdict,
} from "./evidence.js";

export {
  ComparedWalletAddress,
  GateLeakRow,
  decodeGateLeakRow,
  decodeGateLeakRows,
  WalletDeploymentOwnership,
  LinkedWalletEvidence,
  SubjectIdentityEvidence,
  SubjectClassificationInput,
  DuplicateWalletDeploymentError,
  DuplicateSubjectIdentityError,
  decodeSubjectClassificationInput,
  classifyGateLeakSubject,
  classifyGateLeakSubjects,
  DisclosureBand,
  disclosureBand,
  coverageBandFloorPercent,
  meetsCoverageThreshold,
  GateLeakMeasure,
  decodeGateLeakMeasure,
  computeGateLeakMeasure,
  GateLeakComputeInput,
  decodeGateLeakComputeInput,
  digestGateLeakComputeInput,
  GateLeakDisclosureLedgerKey,
  decodeGateLeakDisclosureKey,
  digestGateLeakDisclosureKey,
  evaluateCohortAdmission,
  evaluateCaptureCompleteness,
  type CohortAdmissionVerdict,
  type CaptureCompletenessVerdict,
} from "./compute.js";

export {
  evaluateGateLeakReadiness,
  type GateLeakReadinessContext,
  type GateLeakReadinessVerdict,
  type GateLeakReadinessEvaluationError,
  type CoverageGapDisclosure,
} from "./readiness.js";

export {
  LegacyDiscrepancyBand,
  LegacyEvidenceQuality,
  LegacyGateLeakRecord,
  decodeLegacyGateLeakRecord,
  migrateLegacyGateLeakRecord,
  type MigratedGateLeakRecord,
} from "./migration.js";
