#!/usr/bin/env node
// =============================================================================
// events:new-schema — one-command new event family (cycle-112 T3.5, FR-ADOPT-3).
//
// The adoption carrot: adding a new ACVP event must be MORE work WITHOUT this
// generator than with it, so the compliant path is the path of least resistance
// (NFR-Ergo-2). One command scaffolds a compiling, registry-wired skeleton:
//
//   node scripts/new-schema.mjs <family> [--aggregate a --noun n --verb v --version 1]
//   e.g. node scripts/new-schema.mjs kill-switch-signal \
//        --aggregate internal --noun killswitch --verb signalled
//
// It (1) writes src/schemas/<family>.ts (an S.Struct stub), (2) appends a typed
// registry entry at the ENTRIES marker in src/registry.ts, (3) exports the
// SchemaId from src/index.ts at the marker, and (4) prints the stub aspirational
// `acvp_invariant` to paste into the owning beacon. The developer only fills in
// the S.Struct fields. Graduates to a `freeside events:new-schema` verb later.
//
// Idempotency: refuses if the schema file already exists.
// =============================================================================

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const PKG = join(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const family = args.find((a) => !a.startsWith("--"));
if (!family || !/^[a-z][a-z0-9-]*$/.test(family)) {
  console.error("usage: new-schema <family-kebab> [--aggregate a --noun n --verb v --version N]");
  console.error("  <family> must be lowercase kebab-case (e.g. parallel-mode-enabled)");
  process.exit(2);
}
const flag = (name, def) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 && args[i + 1] ? args[i + 1] : def;
};
// Default topic segments derive from the family (best-effort; override via flags).
const parts = family.split("-");
const aggregate = flag("aggregate", parts[0]);
const noun = flag("noun", parts[1] ?? parts[0]);
const verb = flag("verb", parts[2] ?? parts[parts.length - 1]);
const version = flag("version", "1");
const familyId = `${aggregate}.${noun}.${verb}.v${version}`;

// PascalCase symbol from the kebab family.
const Pascal = family.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const SchemaSym = `${Pascal}Schema`;
const IdSym = `${Pascal}Id`;
const TopicFn = `${Pascal.charAt(0).toLowerCase()}${Pascal.slice(1)}Topic`;

const schemaPath = join(PKG, "src", "schemas", `${family}.ts`);
if (existsSync(schemaPath)) {
  console.error(`[new-schema] ${schemaPath} already exists — refusing to overwrite.`);
  process.exit(1);
}

// 1) the schema file (validation-only S.Struct stub).
const schemaSrc = `import { Schema as S } from "@effect/schema";

/**
 * Payload schema for \`${familyId}\` events (generated by events:new-schema).
 *
 * VALIDATION-ONLY: do not add S.transform/coercion (the registry signs the
 * ORIGINAL payload — a lossy transform diverges the signed bytes; cycle-112
 * SKP-004). If you genuinely need coercion, set \`transform: true\` on the
 * registry entry AND add its id to REVIEWED_TRANSFORMS.
 *
 * TODO: replace the placeholder field with the real payload shape.
 */
export const ${SchemaSym} = S.Struct({
  // TODO: real fields. Placeholder so the skeleton compiles + the registry wires.
  placeholder: S.String,
});

export type ${Pascal} = S.Schema.Type<typeof ${SchemaSym}>;
`;
writeFileSync(schemaPath, schemaSrc);

// 2) a topic helper appended to topics.ts.
const topicsPath = join(PKG, "src", "topics.ts");
const topicHelper = `
// --- ${familyId} (generated by events:new-schema) ------------------------------
export function ${TopicFn}(opts: { specifier?: string } = {}): string {
  return buildTopic({
    aggregate: ${JSON.stringify(aggregate)},
    noun: ${JSON.stringify(noun)},
    verb: ${JSON.stringify(verb)},
    specifier: opts.specifier,
    version: ${version},
  });
}
`;
writeFileSync(topicsPath, readFileSync(topicsPath, "utf8").replace(/\s*$/, "\n") + topicHelper);

// 3) registry entry at the ENTRIES marker + the SchemaId export.
const REG_MARKER = "  // pilot + migrated entries appended here (cycle-112 S3/S4)";
let reg = readFileSync(join(PKG, "src", "registry.ts"), "utf8");
if (!reg.includes(REG_MARKER)) {
  console.error("[new-schema] registry.ts ENTRIES marker missing — insert manually.");
  process.exit(1);
}
const idDecl = `export const ${IdSym}: SchemaId<S.Schema.Type<typeof ${SchemaSym}>> = schemaId(
  ${JSON.stringify(familyId)},
  ${SchemaSym},
);
`;
const entry = `  {
    id: ${IdSym},
    schema: ${SchemaSym},
    buildSubject: (specifier?: string) => ${TopicFn}({ specifier }),
  },
${REG_MARKER}`;
// BB F3: inject TopicFn into the existing topics.js import via a tolerant regex
// (NOT a literal single-import match, which stops matching after the first
// generation once the import line gains a second name → silent no-op → broken
// registry.ts on run N>1). This appends before the closing `}` regardless of how
// many names the import already carries; idempotent across runs.
const topicsImportRx = /(import\s*\{[^}]*?)\s*\}\s*from\s*["']\.\/topics\.js["'];/;
if (!topicsImportRx.test(reg)) {
  console.error('[new-schema] registry.ts import from "./topics.js" not found — insert manually.');
  process.exit(1);
}
reg = reg
  .replace(topicsImportRx, (_m, names) => `${names.trimEnd()}, ${TopicFn} } from "./topics.js";`)
  .replace(
    `import { NftMintDetectedSchema } from "./schemas/nft-mint-detected.js";`,
    `import { NftMintDetectedSchema } from "./schemas/nft-mint-detected.js";\nimport { ${SchemaSym} } from "./schemas/${family}.js";`,
  )
  .replace(
    `export const NftMintDetectedId:`,
    `${idDecl}\nexport const NftMintDetectedId:`,
  )
  .replace(REG_MARKER, entry);
writeFileSync(join(PKG, "src", "registry.ts"), reg);

// 4) export from index.ts at the registry export block.
let idx = readFileSync(join(PKG, "src", "index.ts"), "utf8");
idx = idx.replace("  NftMintDetectedId,\n", `  NftMintDetectedId,\n  ${IdSym},\n`);
writeFileSync(join(PKG, "src", "index.ts"), idx);

console.log(`[new-schema] scaffolded ${family}:`);
console.log(`  + src/schemas/${family}.ts        (fill in S.Struct fields)`);
console.log(`  + src/topics.ts::${TopicFn}`);
console.log(`  + src/registry.ts  (entry ${IdSym} → ${familyId})`);
console.log(`  + src/index.ts     (exports ${IdSym})`);
console.log("");
console.log("  stub acvp_invariant for the owning beacon:");
console.log(`    - id: schema_enforcement`);
console.log(`      scope: "${familyId} payloads are validated at emit-time"`);
console.log(`      proof_artifact: "tests/acvp/schema_enforcement.test.ts"`);
console.log(`      runtime_class: envelope`);
console.log(`      status: aspirational   # promote to active when the proof lands`);
console.log("");
console.log("  next: fill the S.Struct, then `pnpm build` (compiles + collision-checks).");
