#!/usr/bin/env node
// =============================================================================
// sync-vitest.mjs — Sprint-1 T4 · FR-1 (manifest → vitest sidecar)
// =============================================================================
// The extraction-manifest.yaml quarantine[] list is the SoT for which test
// files the required suite excludes. vitest.workspace.ts can't read YAML, so we
// project the file list into a committed JSON sidecar the config imports:
//   themes/sietch/tests/quarantine.generated.json
//
// Modes:
//   node tools/quarantine/sync-vitest.mjs            # regenerate the sidecar
//   node tools/quarantine/sync-vitest.mjs --check     # CI: fail if sidecar drifts
//
// Keeping it derived (generate + sync-check) means nobody hand-edits the exclude
// list out of agreement with the manifest. Exit: 0 ok, 1 drift (--check), 2 env.
// =============================================================================
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..');
const MANIFEST = resolve(ROOT, 'tools/extraction/extraction-manifest.yaml');
const SIDECAR = resolve(ROOT, 'themes/sietch/tests/quarantine.generated.json');
const check = process.argv.includes('--check');

if (!existsSync(MANIFEST)) { console.error(`::error::manifest not found: ${MANIFEST}`); process.exit(2); }

let manifest;
try {
  const out = execFileSync('python3',
    ['-c', 'import sys,yaml,json;json.dump(yaml.safe_load(open(sys.argv[1])) or {},sys.stdout,default=str)', MANIFEST],
    { encoding: 'utf8' });
  manifest = JSON.parse(out);
} catch (e) {
  console.error(`::error::cannot read manifest (need python3 + pyyaml): ${e.message.split('\n')[0]}`);
  process.exit(2);
}

const files = (manifest.quarantine || [])
  .map((q) => q && q.file)
  .filter((f) => typeof f === 'string' && f.length > 0)
  .sort();

const payload = {
  _comment: 'GENERATED by tools/quarantine/sync-vitest.mjs from extraction-manifest.yaml quarantine[]. Do not hand-edit — edit the manifest and re-run.',
  source: 'tools/extraction/extraction-manifest.yaml',
  files,
};
const next = JSON.stringify(payload, null, 2) + '\n';

if (check) {
  const current = existsSync(SIDECAR) ? readFileSync(SIDECAR, 'utf8') : '';
  if (current !== next) {
    console.error('::error::quarantine sidecar out of sync with the manifest — run: node tools/quarantine/sync-vitest.mjs');
    process.exit(1);
  }
  console.log(`✓ quarantine sidecar in sync (${files.length} excluded file(s))`);
  process.exit(0);
}

writeFileSync(SIDECAR, next);
console.log(`✓ wrote ${SIDECAR.replace(ROOT + '/', '')} — ${files.length} excluded file(s): ${files.join(', ') || '(none)'}`);
